### ISSUE TITLE
Support on Xcode 17 and iOS 15

### ISSUE THREAD

**Issue by JanHalozan** [ReMVVM/ReMVVM#3]
Are there any plans to update this framework to work with the new versions of xcode, swift and iOS? I noticed that trying to build on latest xcode and OS it gives an error:
```
ReMVVMRxSwift/Sources/ReMVVM+Rx.swift:75:19 Type 'Reactive<Base>.ReactiveObserver2' does not conform to protocol 'StateObserver'
```

It looks like it's just missing an explicit `typealias State = Base.State.Wrapped`

**Comment by dgrzeszczak** [comment]
Hey Jan, change is pushed to the repo, thanks
